spring.application.name=exceptionapp




spring.application.name=exceptionapp
# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/exceptiondb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=2006_18


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



