spring.application.name=swaggerdemo

spring.datasource.url=jdbc:mysql://localhost:3306/swaggerdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=2006_18

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true