spring.application.name=Relationshipmapping


spring.application.name=relationshipmapping
# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/rmdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=2006_18


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


